### ISSUE TITLE
Add link to github repository...

### ISSUE THREAD

**Issue by fingolfin** [gapdays/gapdays.github.io#2]
... something like an "Edit" link, which when clicked, leads to the corresponding github repository entry.

I have seen similar things done for other repositories, shouldn't be too hard.

**Comment by olexandr-konovalov** [comment]
This works: https://github.com/gapdays/gap-sage-days2016/commit/b1fe5c25c5534b69f952b6d84e913963c3d682ac - if looks  OK, just copy this to the template.

**Comment by olexandr-konovalov** [comment]
Even this - corrects copypasting error: https://github.com/gapdays/gap-sage-days2016/commit/e3b8629c32dc957415e0633177036835529f8871

**Comment by fingolfin** [comment]
Yes, that would be a good start -- though I would prefer if it did not appear as part of the regular navigation, it is easy to overlook and / or misunderstand. Perhaps it could be moved to the bottom of the navbar?  Or simply switch to a smaller font, and / or in a darker color (like the dates in the navbar), or so...

**Comment by fingolfin** [comment]
And then the same edit link could be also added to all previous gap day pages ;-)

**Comment by olexandr-konovalov** [comment]
@fingolfin: agree about bottom of navbar or at least different font. I've took the HTML from [here](http://opendreamkit.org/) but that page has all navbar aligned to the bottom of the page. Let's first make a good design for https://github.com/gapdays/gap-sage-days2016/ and then replicate it to all previous GAP days.

A good approach could be to have a template for GAP Days so that each GAP Days site could pull from the template to update its layout without overwriting the content.

**Comment by fingolfin** [comment]
I implemented an edit button on all gapdays pages now. 

In the orginal design of the gapdays pages, I quite deliberately chose not to use a common template for all sites -- the problem with that is that updates to the templates tend to break older pages, without anybody noticing. There are countless examples of this happening on the net. So, instead, I made the pages self-contained. There is rarely need to "improve" old conference pages in the future, after all;  preserving them in a usable state for future reference seems much more important...
